### ISSUE TITLE
tama_collapse.py different issue in sam and bam

### ISSUE THREAD

**Issue by xiaonalu** [GenomeRIK/tama#60]
Hello,
**when I use sam as input, I received this error "Traceback (most recent call last):**
  File "/conda_envs/gs-tama/bin/tama_collapse.py", line 5123, in <module>
    sam_flag = int(line_split[1])
ValueError: invalid literal for int() with base 10: '\xd5fJ2\x89\xefw\xa8'" 

**Then I use samtools to generate a sorted bam from my initial fastq as input, while received a different error:**
Traceback (most recent call last):
  File "/conda_envs/gs-tama/bin/tama_collapse.py", line 207, in <module>
    sam_file = opts.s[0]
TypeError: 'NoneType' object has no attribute '__getitem__'

I guess something wrong with my mapping step, which I use “minimap2 -ax splice -t 30 -uf --secondary=no GRCm39.fa mousecap.fasta > mousecap.sam” The mapping went smoothly without error report.

Could you please guide me on it? Thanks
Best
Xiaona

**Comment by xiaonalu** [comment]
Ummm... I think I found the problem... it's because the SAMtools...
