### ISSUE TITLE
help needed in format converter 

### ISSUE THREAD

**Issue by zmz1988** [GenomeRIK/tama#75]
Hi, Thanks for writing the scripts for Isoseq analyses!

I'm trying to convert all of my gtf file and gff file to bed12 format for tama_merge. But somehow it complains "gene_id" is not found, though the gene_id is in my input file. 

For example, I had tried 
```
`$ python /tama/tama_go/format_converter/tama_format_gff_to_bed12_cupcake.py sqanti3/sample_classification.filtered_lite.gtf tama_result/sample_classification.filtered_lite.bed`

opening gff file
Going through gtf file
Traceback (most recent call last):
  File "/tama/tama_go/format_converter/tama_format_gff_to_bed12_cupcake.py", line 154, in <module>
    if trans_id not in gene_dict[gene_id]:
NameError: name 'gene_id' is not defined
```

But actually my gtf file has the gene_id line, and the format is the same as cupcake.gff (I think so, please correct me if I'm wrong) 
```
(SQANTI3.env) $ head sqanti3/sample_classification.filtered_lite.gtf
Chr1_RagTag_p	PacBio	transcript	50836	52634	.	-	.	transcript_id "PB.1.1"; gene_id "PB.1";
Chr1_RagTag_p	PacBio	exon	50836	51333	.	-	.	transcript_id "PB.1.1"; gene_id "PB.1";
Chr1_RagTag_p	PacBio	exon	51426	52203	.	-	.	transcript_id "PB.1.1"; gene_id "PB.1";
Chr1_RagTag_p	PacBio	exon	52287	52634	.	-	.	transcript_id "PB.1.1"; gene_id "PB.1";
Chr1_RagTag_p	PacBio	transcript	50948	52640	.	-	.	transcript_id "PB.1.2"; gene_id "PB.1";
Chr1_RagTag_p	PacBio	exon	50948	51333	.	-	.	transcript_id "PB.1.2"; gene_id "PB.1";
Chr1_RagTag_p	PacBio	exon	51426	52203	.	-	.	transcript_id "PB.1.2"; gene_id "PB.1";
Chr1_RagTag_p	PacBio	exon	52287	52640	.	-	.	transcript_id "PB.1.2"; gene_id "PB.1";
Chr1_RagTag_p	PacBio	transcript	60581	62478	.	-	.	transcript_id "PB.2.1"; gene_id "PB.2";
Chr1_RagTag_p	PacBio	exon	60581	62478	.	-	.	transcript_id "PB.2.1"; gene_id "PB.2";
```

I tried to convert the `sqanti3/sample_classification.filtered_lite.gtf` to bed12 by using `gff3_file_to_bed.pl` from TransDecoder, but the resulted bed file is like this, which has no "gene_id" and "transcript_id".
```
$ head sample_corrected.gtf.cds.bed
Chr1_RagTag_p	50835	52634	Chr1_RagTag_p-_g_9757;PB.1.1	40	-	51055	52517	255,0,0	3	498,778,348	0,590,1451
Chr1_RagTag_p	50947	52640	Chr1_RagTag_p-_g_9757;PB.1.2	40	-	51055	52517	255,0,0	3	386,778,354	0,478,1339
Chr1_RagTag_p	60580	62478	Chr1_RagTag_p-_g_9760;PB.2.1	40	-	60742	62329	255,0,0	1	1898	0
Chr1_RagTag_p	67530	70976	Chr1_RagTag_p-_g_9762;PB.3.1	40	-	67748	70863	255,0,0	14	296,75,57,117,108,126,90,126,54,81,108,72,63,302	0,402,571,721,930,1151,1383,1559,1927,2082,2270,2498,2655,3144
Chr1_RagTag_p	67649	70976	Chr1_RagTag_p-_g_9762;PB.3.2	40	-	67748	70863	255,0,0	14	177,75,57,117,108,126,90,126,54,81,108,72,63,302	0,283,452,602,811,1032,1264,1440,1808,1963,2151,2379,2536,3025
Chr1_RagTag_p	75695	77397	Chr1_RagTag_p+_g_9765;PB.4.1	40	+	75933	77234	255,0,0	5	325,77,109,253,225	0,742,942,1143,1477
Chr1_RagTag_p	112380	114891	Chr1_RagTag_p+_g_9776;PB.5.1	40	+	112945	114718	255,0,0	1	2511	0
Chr1_RagTag_p	112420	114996	Chr1_RagTag_p+_g_9776;PB.5.2	40	+	112945	114718	255,0,0	2	261,2240	0,336
Chr1_RagTag_p	112424	114901	Chr1_RagTag_p+_g_9776;PB.5.3	40	+	112945	114718	255,0,0	2	257,2138	0,339
Chr1_RagTag_p	120384	121986	Chr1_RagTag_p+_g_9779;PB.6.2	40	+	120415	121873	255,0,0	1	1602	0
```

May I ask whether I did something wrong, which results in the error in the script? If yes, could you please give me some hints to solve this problem?

Also, I have two gff3 file that I would like to convert to be the inputs of Tama_merge, and their format is like below
```
##gff-version 3
# Liftoff v1.6.3

Chr1_RagTag_polished    Liftoff gene    6983    9251    .       +       .       ID=AT1G01010;Note=protein_coding_gene;Name=AT1G01010;coverage=1.0;sequence_ID=1.0;valid_ORFs=1;extra_copy_number=0;copy_num_ID=AT1G01010_0
Chr1_RagTag_polished    Liftoff mRNA    6983    9251    .       +       .       ID=AT1G01010.1;Parent=AT1G01010;Name=AT1G01010.1;Index=1;matches_ref_protein=True;valid_ORF=True;extra_copy_number=0
Chr1_RagTag_polished    Liftoff exon    6983    7265    .       +       .       ID=exon_1;Parent=AT1G01010.1;extra_copy_number=0
Chr1_RagTag_polished    Liftoff exon    7348    7628    .       +       .       ID=exon_2;Parent=AT1G01010.1;extra_copy_number=0
Chr1_RagTag_polished    Liftoff exon    7838    7957    .       +       .       ID=exon_3;Parent=AT1G01010.1;extra_copy_number=0
Chr1_RagTag_polished    Liftoff exon    8058    8447    .       +       .       ID=exon_4;Parent=AT1G01010.1;extra_copy_number=0
Chr1_RagTag_polished    Liftoff exon    8526    8678    .       +       .       ID=exon_5;Parent=AT1G01010.1;extra_copy_number=0
Chr1_RagTag_polished    Liftoff exon    8791    9251    .       +       .       ID=exon_6;Parent=AT1G01010.1;extra_copy_number=0
Chr1_RagTag_polished    Liftoff CDS     7112    7265    .       +       .       ID=CDS_1;Parent=AT1G01010.1,AT1G01010.1-Protein;extra_copy_number=0
Chr1_RagTag_polished    Liftoff CDS     7348    7628    .       +       .       ID=CDS_2;Parent=AT1G01010.1,AT1G01010.1-Protein;extra_copy_number=0
Chr1_RagTag_polished    Liftoff CDS     7838    7957    .       +       .       ID=CDS_3;Parent=AT1G01010.1,AT1G01010.1-Protein;=;extra_copy_number=0
Chr1_RagTag_polished    Liftoff CDS     8058    8447    .       +       .       ID=CDS_4;Parent=AT1G01010.1,AT1G01010.1-Protein;=;extra_copy_number=0
Chr1_RagTag_polished    Liftoff CDS     8526    8678    .       +       .       ID=CDS_5;Parent=AT1G01010.1,AT1G01010.1-Protein;=;extra_copy_number=0
Chr1_RagTag_polished    Liftoff CDS     8791    8982    .       +       .       ID=CDS_6;Parent=AT1G01010.1,AT1G01010.1-Protein;=;extra_copy_number=0
Chr1_RagTag_polished    Liftoff five_prime_UTR  6983    7111    .       +       .       ID=five_prime_UTR_1;Parent=AT1G01010.1;extra_copy_number=0
Chr1_RagTag_polished    Liftoff three_prime_UTR 8983    9251    .       +       .       ID=three_prime_UTR_1;Parent=AT1G01010.1;extra_copy_number=0

```

I tried to convert the gff3 file into bed12 by using the same script from TransDecoder, but the resulted bed file also lacks "gene_id" and "transcript_id". Do you mind to give me a hand on converting these files to fit into tame_merge format?

Thanks a lot!

**Comment by GenomeRIK** [comment]
Hello,

Thanks for using TAMA!

For the first file you tried to run in the first example you showed, can you double check to see if you have any empty or incomplete lines? For instance at the end of file? Can you also check for invisible formatting issues using cat -A? Can you copy and paste some of lines from the output of "cat -A"?

Cheers,
Richard

**Comment by zmz1988** [comment]
Hi Richard,

Thanks for replying me! Here is a few lines from cat -A
```
`(base) $ cat -A Col_final_23022022_new_hapog_patch_hapog_reorder_classification.filtered_lite.gtf | head`
Chr1_RagTag_p^IPacBio^Itranscript^I50836^I52634^I.^I-^I.^Itranscript_id "PB.1.1"; gene_id "PB.1";$
Chr1_RagTag_p^IPacBio^Iexon^I50836^I51333^I.^I-^I.^Itranscript_id "PB.1.1"; gene_id "PB.1";$
Chr1_RagTag_p^IPacBio^Iexon^I51426^I52203^I.^I-^I.^Itranscript_id "PB.1.1"; gene_id "PB.1";$
Chr1_RagTag_p^IPacBio^Iexon^I52287^I52634^I.^I-^I.^Itranscript_id "PB.1.1"; gene_id "PB.1";$
Chr1_RagTag_p^IPacBio^Itranscript^I50948^I52640^I.^I-^I.^Itranscript_id "PB.1.2"; gene_id "PB.1";$
Chr1_RagTag_p^IPacBio^Iexon^I50948^I51333^I.^I-^I.^Itranscript_id "PB.1.2"; gene_id "PB.1";$
Chr1_RagTag_p^IPacBio^Iexon^I51426^I52203^I.^I-^I.^Itranscript_id "PB.1.2"; gene_id "PB.1";$
Chr1_RagTag_p^IPacBio^Iexon^I52287^I52640^I.^I-^I.^Itranscript_id "PB.1.2"; gene_id "PB.1";$
Chr1_RagTag_p^IPacBio^Itranscript^I60581^I62478^I.^I-^I.^Itranscript_id "PB.2.1"; gene_id "PB.2";$
Chr1_RagTag_p^IPacBio^Iexon^I60581^I62478^I.^I-^I.^Itranscript_id "PB.2.1"; gene_id "PB.2";$

`(base) $ cat -A Col_final_23022022_new_hapog_patch_hapog_reorder_classification.filtered_lite.gtf | tail`
ChrC_RagTag_p^IPacBio^Iexon^I329052^I332542^I.^I+^I.^Itranscript_id "PB.6950.1"; gene_id "PB.6950";$
ChrC_RagTag_p^IPacBio^Itranscript^I330338^I332542^I.^I+^I.^Itranscript_id "PB.6950.2"; gene_id "PB.6950";$
ChrC_RagTag_p^IPacBio^Iexon^I330338^I332542^I.^I+^I.^Itranscript_id "PB.6950.2"; gene_id "PB.6950";$
ChrC_RagTag_p^IPacBio^Itranscript^I344688^I346382^I.^I+^I.^Itranscript_id "PB.6952.9"; gene_id "PB.6952";$
ChrC_RagTag_p^IPacBio^Iexon^I344688^I346382^I.^I+^I.^Itranscript_id "PB.6952.9"; gene_id "PB.6952";$
ChrC_RagTag_p^IPacBio^Itranscript^I422227^I424156^I.^I+^I.^Itranscript_id "PB.6959.1"; gene_id "PB.6959";$
ChrC_RagTag_p^IPacBio^Iexon^I422227^I424156^I.^I+^I.^Itranscript_id "PB.6959.1"; gene_id "PB.6959";$
ChrC_RagTag_p^IPacBio^Itranscript^I422334^I424156^I.^I+^I.^Itranscript_id "PB.6959.2"; gene_id "PB.6959";$
ChrC_RagTag_p^IPacBio^Iexon^I422334^I423092^I.^I+^I.^Itranscript_id "PB.6959.2"; gene_id "PB.6959";$
ChrC_RagTag_p^IPacBio^Iexon^I423775^I424156^I.^I+^I.^Itranscript_id "PB.6959.2"; gene_id "PB.6959";$

```

**Comment by GenomeRIK** [comment]
Hello,

Ok sorry that was a stupid mistake on my part. I assumed the gene ID's would come before the transcript ID's. I have fixed this issue so the tama_format_gff_to_bed12_cupcake.py tool should work for you now. 

For the liftoff GFF3, they are using a special sub-format for their gene-transcript-exon associations. I have made a new converter for this based on the example you gave me but I am not sure if it will work on the whole file. You will also need to remove any headers from the file to run. 

The new tool is called:
tama_format_gff_to_bed12_liftoff.py

Cheers,
Richard

**Comment by zmz1988** [comment]
Thanks a lot, @GenomeRIK Richard! I just tried tama_format_gff_to_bed12_cupcake.py, and it gives me an error:

```
(SQANTI3.env) $ python /tama/tama_go/format_converter/tama_format_gff_to_bed12_cupcake.py sqanti3/sample_classification.filtered_lite.gtf tama_result/sample_classification.filtered_lite.gtf.bed
opening gff file
Going through gtf file
writing out file
Traceback (most recent call last):
  File "/tama/tama_go/format_converter/tama_format_gff_to_bed12_cupcake.py", line 185, in <module>
    gene_trans_dict[gene_id][trans_id].finish_bed()
  File "/tama/tama_go/format_converter/tama_format_gff_to_bed12_cupcake.py", line 64, in finish_bed
    exon_num_list.sort()
AttributeError: 'dict_keys' object has no attribute 'sort'
```
Has this something to do my python version? python 3.9?

for the `tama_format_gff_to_bed12_liftoff.py`

I got this error 
```
(SQANTI3.env) $ python /tama/tama_go/format_converter/tama_format_gff_to_bed12_liftoff.py liftoff/sample_liftoff.gff3_polished tama_result/sample_liftoff.gff3_polished.bed
opening gtf file
Going through GFF genes
Going through GFF transcripts
Going through GFF exons/cds/start codon/stop codon/utr
write bed12 file
Traceback (most recent call last):
  File "/tama/tama_go/format_converter/tama_format_gff_to_bed12_liftoff.py", line 510, in <module>
    cds_start = str(trans_dict[trans_id].c_start_list[0])
IndexError: list index out of range
```
Does this error means I have a bad gff file?

Sorry for adding so much to your workload!

**Comment by GenomeRIK** [comment]
Oh yes have you not been using Python 2.7 to run TAMA? TAMA currently is only Python 2.7. If you ran anything else using TAMA please re-do it with Python 2.7.

We will convert to Python 3 in our next version of TAMA which we are working on right now. 

As for the liftoff conversion, is there a way you could send me the file? It is hard to make a converter for a file I can't see. 

Cheers,
Richard

**Comment by zmz1988** [comment]
Oh I'm so sorry!! I had stared at the home page of TAMA many times, but didn't pay attention to the python version! Super sorry for my mistake!

Sure, I can share the file via email. How could I send it to you?

**Comment by GenomeRIK** [comment]
Could you send it to the email shown in the code page?

**Comment by GenomeRIK** [comment]
Ok great!
Feel free to post any other issues you come across. 

Cheers,
Richard
